import type { Atom, AgentProfile, Source, LatticeStats, ContextResult, AuditEntry, ActivityEvent } from './types'

export const mockStats: LatticeStats = {
  total_atoms: 1247,
  total_frames: 38,
  total_agents: 12,
  cache_hit_rate: 0.942,
  atoms_by_kind: {
    fact: 412,
    metric: 298,
    decision: 187,
    relationship: 156,
    event: 104,
    procedure: 90,
  },
}

export const mockAgents: AgentProfile[] = [
  {
    id: 'agent-1',
    name: 'Sales Assistant',
    api_key: 'lat_sa_xxxx',
    purpose: 'Help sales team with pipeline analysis and forecasting',
    domains: ['sales', 'finance'],
    role_mask: 0b00000110, // sales + finance
    max_tokens: 4000,
    query_count: 142,
    avg_latency: 4.2,
    cache_hit_rate: 0.96,
  },
  {
    id: 'agent-2',
    name: 'Engineering Bot',
    api_key: 'lat_eb_xxxx',
    purpose: 'Assist engineers with oncall, infra questions, and incident resolution',
    domains: ['engineering'],
    role_mask: 0b00001000, // engineering
    max_tokens: 8000,
    query_count: 89,
    avg_latency: 6.1,
    cache_hit_rate: 0.91,
  },
  {
    id: 'agent-3',
    name: 'HR Copilot',
    api_key: 'lat_hr_xxxx',
    purpose: 'Answer employee questions about policies, benefits, and hiring',
    domains: ['hr', 'legal'],
    role_mask: 0b00110000, // hr + legal
    max_tokens: 3000,
    query_count: 56,
    avg_latency: 5.8,
    cache_hit_rate: 0.88,
  },
  {
    id: 'agent-4',
    name: 'Executive Briefing',
    api_key: 'lat_ex_xxxx',
    purpose: 'Provide C-suite with cross-functional summaries and key decisions',
    domains: ['sales', 'finance', 'engineering', 'hr', 'product'],
    role_mask: 0b11111111, // all roles
    max_tokens: 6000,
    query_count: 34,
    avg_latency: 8.3,
    cache_hit_rate: 0.82,
  },
]

export const mockSources: Source[] = [
  {
    id: 'src-1',
    name: 'Q2-Financial-Report.pdf',
    source_type: 'pdf',
    classification: 'confidential',
    domains: ['finance', 'sales'],
    atom_count: 84,
    frame_count: 3,
    compiled_at: new Date(Date.now() - 120000).toISOString(),
    compilation_stats: {
      atomize_ms: 1200,
      distill_ms: 3400,
      embed_ms: 800,
      link_ms: 1100,
      tag_ms: 200,
      index_ms: 300,
      atoms_by_kind: { fact: 32, metric: 28, decision: 12, relationship: 8, event: 3, procedure: 1 },
    },
  },
  {
    id: 'src-2',
    name: 'Engineering-Runbook.pdf',
    source_type: 'pdf',
    classification: 'internal',
    domains: ['engineering'],
    atom_count: 156,
    frame_count: 5,
    compiled_at: new Date(Date.now() - 3600000).toISOString(),
    compilation_stats: {
      atomize_ms: 2100,
      distill_ms: 5200,
      embed_ms: 1200,
      link_ms: 1800,
      tag_ms: 350,
      index_ms: 450,
      atoms_by_kind: { fact: 48, metric: 22, decision: 8, relationship: 34, event: 12, procedure: 32 },
    },
  },
  {
    id: 'src-3',
    name: 'HR-Policy-Handbook.pdf',
    source_type: 'pdf',
    classification: 'internal',
    domains: ['hr', 'legal'],
    atom_count: 210,
    frame_count: 7,
    compiled_at: new Date(Date.now() - 86400000).toISOString(),
    compilation_stats: {
      atomize_ms: 2800,
      distill_ms: 6100,
      embed_ms: 1500,
      link_ms: 2200,
      tag_ms: 400,
      index_ms: 500,
      atoms_by_kind: { fact: 78, metric: 12, decision: 45, relationship: 28, event: 15, procedure: 32 },
    },
  },
  {
    id: 'src-4',
    name: 'Product-Roadmap-2026.md',
    source_type: 'markdown',
    classification: 'confidential',
    domains: ['product', 'engineering'],
    atom_count: 93,
    frame_count: 4,
    compiled_at: new Date(Date.now() - 7200000).toISOString(),
    compilation_stats: {
      atomize_ms: 900,
      distill_ms: 2800,
      embed_ms: 600,
      link_ms: 900,
      tag_ms: 180,
      index_ms: 250,
      atoms_by_kind: { fact: 24, metric: 8, decision: 22, relationship: 18, event: 11, procedure: 10 },
    },
  },
]

const salesAtoms: Atom[] = [
  {
    id: 'atom-s1',
    content: 'EMEA Q2 pipeline stands at $4.2M, representing a 12% increase from Q1 driven by enterprise expansion in the DACH region.',
    kind: 'metric',
    domain: ['sales', 'finance'],
    confidence: 0.94,
    freshness: new Date(Date.now() - 7200000).toISOString(),
    source_id: 'src-1',
    source_name: 'Q2-Financial-Report.pdf',
    links: [{ target_id: 'atom-s2', relation: 'supports' }],
    version: 3,
  },
  {
    id: 'atom-s2',
    content: 'Board approved EMEA expansion budget in April, allocating $1.8M for enterprise sales team growth across 3 offices.',
    kind: 'decision',
    domain: ['sales', 'finance'],
    confidence: 0.89,
    freshness: new Date(Date.now() - 14400000).toISOString(),
    source_id: 'src-1',
    source_name: 'Q2-Financial-Report.pdf',
    links: [{ target_id: 'atom-s1', relation: 'justifies' }],
    version: 2,
  },
  {
    id: 'atom-s3',
    content: 'Top 3 enterprise deals: Acme Corp ($800K, 90% close probability), Globex Industries ($650K, 75%), Initech Systems ($500K, 60%).',
    kind: 'metric',
    domain: ['sales'],
    confidence: 0.92,
    freshness: new Date(Date.now() - 3600000).toISOString(),
    source_id: 'src-1',
    source_name: 'Q2-Financial-Report.pdf',
    links: [],
    version: 4,
  },
  {
    id: 'atom-s4',
    content: 'Q2 sales team headcount increased to 34 (from 28 in Q1), with 4 new enterprise AEs focused on DACH and Nordics.',
    kind: 'fact',
    domain: ['sales', 'hr'],
    confidence: 0.88,
    freshness: new Date(Date.now() - 86400000).toISOString(),
    source_id: 'src-1',
    source_name: 'Q2-Financial-Report.pdf',
    links: [{ target_id: 'atom-s2', relation: 'result_of' }],
    version: 1,
  },
  {
    id: 'atom-s5',
    content: 'Average deal cycle shortened from 68 days to 52 days after implementing the new qualification framework in March.',
    kind: 'metric',
    domain: ['sales'],
    confidence: 0.91,
    freshness: new Date(Date.now() - 43200000).toISOString(),
    source_id: 'src-1',
    source_name: 'Q2-Financial-Report.pdf',
    links: [],
    version: 2,
  },
  {
    id: 'atom-s6',
    content: 'Customer churn rate decreased to 3.2% (from 4.8%) following the renewal incentive program launched in Q1.',
    kind: 'metric',
    domain: ['sales', 'finance'],
    confidence: 0.87,
    freshness: new Date(Date.now() - 172800000).toISOString(),
    source_id: 'src-1',
    source_name: 'Q2-Financial-Report.pdf',
    links: [],
    version: 1,
  },
  {
    id: 'atom-s7',
    content: 'Strategic partnership signed with Salesforce for co-selling in enterprise segment, expected to generate $2M in pipeline.',
    kind: 'event',
    domain: ['sales'],
    confidence: 0.85,
    freshness: new Date(Date.now() - 259200000).toISOString(),
    source_id: 'src-1',
    source_name: 'Q2-Financial-Report.pdf',
    links: [{ target_id: 'atom-s1', relation: 'contributes_to' }],
    version: 1,
  },
  {
    id: 'atom-s8',
    content: 'Approved hiring plan for 6 additional SDRs in Q3 to support APAC market entry.',
    kind: 'decision',
    domain: ['sales', 'hr'],
    confidence: 0.83,
    freshness: new Date(Date.now() - 604800000).toISOString(),
    source_id: 'src-1',
    source_name: 'Q2-Financial-Report.pdf',
    links: [],
    version: 1,
  },
]

const engAtoms: Atom[] = [
  {
    id: 'atom-e1',
    content: 'Platform uptime for Q2: 99.97% (target: 99.95%). Only 3 P1 incidents, all resolved within 4h MTTR.',
    kind: 'metric',
    domain: ['engineering'],
    confidence: 0.91,
    freshness: new Date(Date.now() - 3600000).toISOString(),
    source_id: 'src-2',
    source_name: 'Engineering-Runbook.pdf',
    links: [{ target_id: 'atom-e2', relation: 'measured_by' }],
    version: 5,
  },
  {
    id: 'atom-e2',
    content: '3 P1 incidents in Q2: database failover (Apr 3), CDN cache poisoning (Apr 18), auth service OOM (May 2). All resolved under 4h MTTR.',
    kind: 'fact',
    domain: ['engineering'],
    confidence: 0.88,
    freshness: new Date(Date.now() - 7200000).toISOString(),
    source_id: 'src-2',
    source_name: 'Engineering-Runbook.pdf',
    links: [{ target_id: 'atom-e1', relation: 'details' }],
    version: 3,
  },
  {
    id: 'atom-e3',
    content: 'Infrastructure team prioritizing Kubernetes migration over new feature work in Q3. Target: 80% of services on K8s by end of Q3.',
    kind: 'decision',
    domain: ['engineering'],
    confidence: 0.85,
    freshness: new Date(Date.now() - 14400000).toISOString(),
    source_id: 'src-2',
    source_name: 'Engineering-Runbook.pdf',
    links: [],
    version: 2,
  },
  {
    id: 'atom-e4',
    content: 'API latency p99 reduced from 340ms to 180ms after the caching layer upgrade deployed in April.',
    kind: 'metric',
    domain: ['engineering'],
    confidence: 0.90,
    freshness: new Date(Date.now() - 28800000).toISOString(),
    source_id: 'src-2',
    source_name: 'Engineering-Runbook.pdf',
    links: [],
    version: 2,
  },
  {
    id: 'atom-e5',
    content: 'Engineering headcount: 48 engineers across 6 teams. 4 open positions (2 SRE, 1 Staff Backend, 1 Security).',
    kind: 'fact',
    domain: ['engineering', 'hr'],
    confidence: 0.86,
    freshness: new Date(Date.now() - 172800000).toISOString(),
    source_id: 'src-2',
    source_name: 'Engineering-Runbook.pdf',
    links: [],
    version: 1,
  },
  {
    id: 'atom-e6',
    content: 'Oncall rotation follows sun-follow-the-sun model across US-West, EU-Central, and APAC-East timezones.',
    kind: 'procedure',
    domain: ['engineering'],
    confidence: 0.93,
    freshness: new Date(Date.now() - 604800000).toISOString(),
    source_id: 'src-2',
    source_name: 'Engineering-Runbook.pdf',
    links: [],
    version: 1,
  },
]

export function getMockContextResult(agentId: string, query: string): ContextResult {
  if (agentId === 'agent-1') {
    return {
      query,
      agent: 'Sales Assistant',
      atoms: salesAtoms,
      frame_id: 'frame-sales-q2',
      cache_tier: 'L2',
      latency_ms: 3.2,
      total_tokens: 1840,
      atoms_served: 8,
      atoms_filtered: 2,
    }
  }
  if (agentId === 'agent-2') {
    return {
      query,
      agent: 'Engineering Bot',
      atoms: engAtoms,
      frame_id: 'frame-eng-q2',
      cache_tier: 'L3',
      latency_ms: 41,
      total_tokens: 1220,
      atoms_served: 6,
      atoms_filtered: 5,
    }
  }
  if (agentId === 'agent-3') {
    return {
      query,
      agent: 'HR Copilot',
      atoms: [
        {
          id: 'atom-h1',
          content: 'Updated PTO policy: Unlimited PTO effective Q2 2026 for all full-time employees. Manager approval required for >5 consecutive days.',
          kind: 'fact',
          domain: ['hr'],
          confidence: 0.95,
          freshness: new Date(Date.now() - 86400000).toISOString(),
          source_id: 'src-3',
          source_name: 'HR-Policy-Handbook.pdf',
          links: [],
          version: 2,
        },
        {
          id: 'atom-h2',
          content: 'Benefits enrollment window opens June 1-15 for Q3. New dental provider (Delta Dental) replaces previous carrier.',
          kind: 'event',
          domain: ['hr'],
          confidence: 0.92,
          freshness: new Date(Date.now() - 172800000).toISOString(),
          source_id: 'src-3',
          source_name: 'HR-Policy-Handbook.pdf',
          links: [],
          version: 1,
        },
        {
          id: 'atom-h3',
          content: 'Company-wide hiring freeze lifted for engineering and sales roles. HR and legal roles remain frozen through Q3.',
          kind: 'decision',
          domain: ['hr', 'legal'],
          confidence: 0.88,
          freshness: new Date(Date.now() - 259200000).toISOString(),
          source_id: 'src-3',
          source_name: 'HR-Policy-Handbook.pdf',
          links: [],
          version: 1,
        },
      ],
      cache_tier: 'L3',
      latency_ms: 38,
      total_tokens: 680,
      atoms_served: 3,
      atoms_filtered: 8,
    }
  }
  // Default: executive
  return {
    query,
    agent: 'Executive Briefing',
    atoms: [...salesAtoms.slice(0, 3), ...engAtoms.slice(0, 2)],
    frame_id: 'frame-exec-q2',
    cache_tier: 'L3',
    latency_ms: 52,
    total_tokens: 2400,
    atoms_served: 5,
    atoms_filtered: 0,
  }
}

export const mockActivity: ActivityEvent[] = [
  {
    id: 'ev-1',
    type: 'query',
    description: 'Sales-Bot queried "Q2 pipeline status"',
    agent: 'Sales Assistant',
    cache_tier: 'L2',
    latency_ms: 3,
    timestamp: new Date(Date.now() - 12000).toISOString(),
  },
  {
    id: 'ev-2',
    type: 'query',
    description: 'Eng-Bot queried "infra incidents Q2"',
    agent: 'Engineering Bot',
    cache_tier: 'L3',
    latency_ms: 41,
    timestamp: new Date(Date.now() - 45000).toISOString(),
  },
  {
    id: 'ev-3',
    type: 'compile',
    description: 'Compiled: Q2-Report.pdf → 84 atoms',
    timestamp: new Date(Date.now() - 120000).toISOString(),
  },
  {
    id: 'ev-4',
    type: 'access_denied',
    description: 'HR-Bot access filtered: 12 atoms (role mismatch)',
    agent: 'HR Copilot',
    timestamp: new Date(Date.now() - 300000).toISOString(),
  },
  {
    id: 'ev-5',
    type: 'query',
    description: 'Exec-Brief queried "company health overview"',
    agent: 'Executive Briefing',
    cache_tier: 'L3',
    latency_ms: 52,
    timestamp: new Date(Date.now() - 600000).toISOString(),
  },
  {
    id: 'ev-6',
    type: 'compile',
    description: 'Compiled: Product-Roadmap-2026.md → 93 atoms',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'ev-7',
    type: 'query',
    description: 'Sales-Bot queried "top enterprise deals"',
    agent: 'Sales Assistant',
    cache_tier: 'L2',
    latency_ms: 2,
    timestamp: new Date(Date.now() - 900000).toISOString(),
  },
  {
    id: 'ev-8',
    type: 'access_denied',
    description: 'Eng-Bot access filtered: 5 atoms (classification level)',
    agent: 'Engineering Bot',
    timestamp: new Date(Date.now() - 1200000).toISOString(),
  },
]

export const mockAuditLog: AuditEntry[] = [
  { id: 'aud-1', timestamp: new Date(Date.now() - 12000).toISOString(), agent_id: 'agent-1', agent_name: 'Sales Assistant', query: 'Q2 pipeline status', atoms_served: 8, atoms_filtered: 2, cache_tier: 'L2', latency_ms: 3 },
  { id: 'aud-2', timestamp: new Date(Date.now() - 45000).toISOString(), agent_id: 'agent-2', agent_name: 'Engineering Bot', query: 'infra incidents Q2', atoms_served: 6, atoms_filtered: 5, cache_tier: 'L3', latency_ms: 41 },
  { id: 'aud-3', timestamp: new Date(Date.now() - 300000).toISOString(), agent_id: 'agent-3', agent_name: 'HR Copilot', query: 'hiring plan status', atoms_served: 0, atoms_filtered: 4, cache_tier: 'L3', latency_ms: 38 },
  { id: 'aud-4', timestamp: new Date(Date.now() - 600000).toISOString(), agent_id: 'agent-4', agent_name: 'Executive Briefing', query: 'company health overview', atoms_served: 12, atoms_filtered: 0, cache_tier: 'L3', latency_ms: 52 },
  { id: 'aud-5', timestamp: new Date(Date.now() - 900000).toISOString(), agent_id: 'agent-1', agent_name: 'Sales Assistant', query: 'top enterprise deals', atoms_served: 5, atoms_filtered: 1, cache_tier: 'L2', latency_ms: 2 },
  { id: 'aud-6', timestamp: new Date(Date.now() - 1500000).toISOString(), agent_id: 'agent-2', agent_name: 'Engineering Bot', query: 'K8s migration timeline', atoms_served: 4, atoms_filtered: 3, cache_tier: 'L3', latency_ms: 45 },
  { id: 'aud-7', timestamp: new Date(Date.now() - 2100000).toISOString(), agent_id: 'agent-1', agent_name: 'Sales Assistant', query: 'EMEA expansion status', atoms_served: 6, atoms_filtered: 2, cache_tier: 'L2', latency_ms: 4 },
  { id: 'aud-8', timestamp: new Date(Date.now() - 2700000).toISOString(), agent_id: 'agent-3', agent_name: 'HR Copilot', query: 'PTO policy update', atoms_served: 3, atoms_filtered: 0, cache_tier: 'L3', latency_ms: 36 },
  { id: 'aud-9', timestamp: new Date(Date.now() - 3300000).toISOString(), agent_id: 'agent-2', agent_name: 'Engineering Bot', query: 'oncall rotation schedule', atoms_served: 8, atoms_filtered: 1, cache_tier: 'L2', latency_ms: 5 },
  { id: 'aud-10', timestamp: new Date(Date.now() - 3900000).toISOString(), agent_id: 'agent-4', agent_name: 'Executive Briefing', query: 'Q2 revenue forecast', atoms_served: 10, atoms_filtered: 0, cache_tier: 'L3', latency_ms: 48 },
]

export const mockQueryTimeline = Array.from({ length: 24 }, (_, i) => ({
  hour: `${String(i).padStart(2, '0')}:00`,
  l2: Math.floor(Math.random() * 30 + 10),
  l3: Math.floor(Math.random() * 8 + 1),
}))
